src/main/java/chathealth/chathealth/entity/member/Address.java, src/main/java/chathealth/chathealth/entity/member/Ent.java, src/main/java/chathealth/chathealth/entity/member/Grade.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/entity/member/Role.java, src/main/java/chathealth/chathealth/entity/member/Users.java
Member 관련 엔티티 생성 완료.
* Member를 상속하는 Users, Ent 객체
* @Getter 적용
* @Inheritance(strategy = InheritanceType.SINGLE_TABLE) 적용
* 유저 vs 사업자 구분하는 DType은 유저 U / 사업자 E 
* Role, Grade ENUM 생성
=> #11 Member entity 생성 완료

src/main/java/chathealth/chathealth/entity/member/Role.java
=> Member entity Role ENUM 오타 수정

build.gradle, src/main/java/chathealth/chathealth/controller/MemberController.java, src/main/java/chathealth/chathealth/dto/response/EntInfoDto.java, src/main/java/chathealth/chathealth/dto/response/MemberInfoDto.java, src/main/java/chathealth/chathealth/dto/response/UserInfoDto.java, src/main/java/chathealth/chathealth/entity/BaseEntity.java, src/main/java/chathealth/chathealth/entity/member/Address.java, src/main/java/chathealth/chathealth/entity/member/Ent.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/entity/member/Users.java, src/main/java/chathealth/chathealth/exception/ChatHealthException.java, src/main/java/chathealth/chathealth/exception/UserNotFound.java, src/main/java/chathealth/chathealth/repository/MemberRepository.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/resources/application.yml, src/test/java/chathealth/chathealth/controller/MemberControllerTest.java, src/test/java/chathealth/chathealth/service/MemberServiceTest.java
Id로 memeber 조회 안될 시 -> UserNotFoundException
일반 유저 조회: Member -> Users 다운 캐스팅
사업자 유저 조회: Member -> Ent 다운 캐스팅
=> feat: 멤버 기본 정보 조회

src/main/java/chathealth/chathealth/controller/AuthController.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/resources/templates/auth/userjoin.html
=> feat: 개인 회원가입 #4 레이아웃 제작

src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/entity/post/Material.java, src/main/java/chathealth/chathealth/entity/post/MaterialPost.java, src/main/java/chathealth/chathealth/entity/post/Post.java, src/main/java/chathealth/chathealth/entity/post/Symptom.java, src/main/java/chathealth/chathealth/entity/post/SymptomPost.java, src/main/resources/application.yml
post, picturepost 엔티티 수정
symptom, material, symptompost, materialpost 생성
수정필요
=> post관련 entity 생성

build.gradle, src/main/java/chathealth/chathealth/config/QueryDslConfig.java
=> feat: querydsl 설정

build.gradle, src/main/java/chathealth/chathealth/controller/PostController.java, src/main/java/chathealth/chathealth/entity/post/Material.java, src/main/java/chathealth/chathealth/entity/post/MaterialPost.java, src/main/java/chathealth/chathealth/entity/post/PicturePost.java, src/main/java/chathealth/chathealth/entity/post/Post.java, src/main/java/chathealth/chathealth/entity/post/Symptom.java, src/main/java/chathealth/chathealth/entity/post/SymptomPost.java, src/main/java/chathealth/chathealth/repository/PostRepository.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/application.yml, src/main/resources/templates/fragment/footer.html, src/main/resources/templates/fragment/header.html, src/main/resources/templates/layout/layout.html, src/main/resources/templates/post/write.html
=> fix: post 관련 엔티티 완료

src/main/java/chathealth/chathealth/dto/request/BoardCreateDto.java, src/main/java/chathealth/chathealth/dto/response/BoardResponse.java, src/main/java/chathealth/chathealth/entity/BoardComment.java, src/main/java/chathealth/chathealth/entity/BoardHit.java, src/main/java/chathealth/chathealth/entity/BoardReply.java, src/main/java/chathealth/chathealth/entity/Likes.java, src/main/java/chathealth/chathealth/entity/PictureBoard.java, src/main/java/chathealth/chathealth/entity/borad/Board.java, src/main/java/chathealth/chathealth/entity/borad/Category.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/exception/BoardNotFoundException.java, src/main/java/chathealth/chathealth/repository/BoardRepository.java, src/main/java/chathealth/chathealth/repository/BoardRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/BoardRepositoryImpl.java, src/main/java/chathealth/chathealth/service/BoardService.java, src/test/java/chathealth/chathealth/service/BoardServiceTest.java
(board, picture_board, board_hit, like, board_comment, board_reply)
=> feat: 게시판 관련 엔티티 생성

src/main/java/chathealth/chathealth/controller/BoardController.java, src/main/java/chathealth/chathealth/dto/request/BoardSearchDto.java, src/main/java/chathealth/chathealth/dto/response/BoardResponse.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/entity/member/Users.java, src/main/java/chathealth/chathealth/repository/BoardRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/board/BoardRepository.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryImpl.java, src/main/java/chathealth/chathealth/service/BoardService.java, src/test/java/chathealth/chathealth/controller/BoardControllerTest.java, src/test/java/chathealth/chathealth/service/BoardServiceTest.java
- 게시물 1개 조회 api 생성
- 게시물 전체 조회 api 생성
- 검색 조건
- category 일치
- title, content, writer 포함 여부
=> feat: 게시물  조회 api

src/main/java/chathealth/chathealth/constants/Constants.java, src/main/java/chathealth/chathealth/controller/BoardController.java, src/main/java/chathealth/chathealth/dto/request/BoardEditDto.java, src/main/java/chathealth/chathealth/dto/request/BoardSearchDto.java, src/main/java/chathealth/chathealth/dto/response/BoardResponse.java, src/main/java/chathealth/chathealth/entity/BoardComment.java, src/main/java/chathealth/chathealth/entity/BoardHit.java, src/main/java/chathealth/chathealth/entity/PictureBoard.java, src/main/java/chathealth/chathealth/entity/board/Board.java, src/main/java/chathealth/chathealth/entity/board/Category.java, src/main/java/chathealth/chathealth/entity/borad/Category.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/exception/NotPermitted.java, src/main/java/chathealth/chathealth/repository/board/BoardRepository.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryImpl.java, src/main/java/chathealth/chathealth/service/BoardService.java, src/test/java/chathealth/chathealth/controller/BoardControllerTest.java, src/test/java/chathealth/chathealth/service/BoardServiceTest.java
boardUpdate -> boardEditDto 객체에서 title, content, category를 받아서 edit
boardDelete -> board entity에 
'@SQLDelete(sql = "UPDATE board SET deleted_date = CURRENT_TIMESTAMP where board_id = ?")' 어노테이션을 사용하여 deletemapping을 통해 delete시 soft delete되도록 함
=> feat: boardUpdate & boardDelete

.gitignore, build.gradle, src/main/java/chathealth/chathealth/config/SecurityConfig.java, src/main/java/chathealth/chathealth/config/WebConfig.java, src/main/java/chathealth/chathealth/controller/AuthController.java, src/main/java/chathealth/chathealth/dto/request/UserJoinDto.java, src/main/java/chathealth/chathealth/repository/MemberRepository.java, src/main/java/chathealth/chathealth/service/AuthService.java, src/main/resources/application.yml, src/main/resources/templates/auth/login.html, src/main/resources/templates/auth/userjoin.html, src/main/resources/templates/layout/layout.html
* 개인 회원가입 유효성 검사 완료
* 프로필 사진 등록 이미지처리 완료
* build.gradle에 썸네일 이미지 생성 도와주는 라이브러리 추가.
=> Feat: userjoin validation & handling img

src/main/java/chathealth/chathealth/config/SecurityConfig.java, src/main/java/chathealth/chathealth/config/WebConfig.java, src/main/java/chathealth/chathealth/constants/Role.java, src/main/java/chathealth/chathealth/controller/BoardRestController.java, src/main/java/chathealth/chathealth/controller/IndexController.java, src/main/java/chathealth/chathealth/controller/PostRestController.java, src/main/java/chathealth/chathealth/dto/response/UserInfoDto.java, src/main/java/chathealth/chathealth/entity/board/Category.java, src/main/java/chathealth/chathealth/entity/post/SymptomType.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/board/BoardRepositoryImpl.java, src/main/java/chathealth/chathealth/repository/post/PostRepositoryCustom.java, src/main/java/chathealth/chathealth/repository/post/PostRepositoryImpl.java, src/main/java/chathealth/chathealth/service/BoardService.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/static/css/layout.css, src/main/resources/templates/fragment/header.html, src/main/resources/templates/index.html, src/main/resources/templates/post/post.html, src/test/java/chathealth/chathealth/controller/BoardRestControllerTest.java
주간, 일간 최다 조회 상품 / 자유게시판, 공지 최신 글 띄움, 로그인 시 프로필 간략 프로필 나오게 함 --> ajax를 통해 4개의 restAPI 호출, 로그인 정보는 권한 정보와 ROLE을 통해 가져옴
=> feat: 메인페이지 초안

src/main/java/chathealth/chathealth/config/SecurityConfig.java, src/main/java/chathealth/chathealth/controller/BoardImageController.java, src/main/java/chathealth/chathealth/controller/IndexController.java, src/main/java/chathealth/chathealth/entity/BoardHit.java, src/main/resources/templates/board/write.html, src/main/resources/templates/fragment/header.html, src/test/java/chathealth/chathealth/controller/MemberControllerTest.java
=> refactor: dbindex적용

src/main/java/chathealth/chathealth/config/SecurityConfig.java, src/main/java/chathealth/chathealth/controller/FileApiController.java, src/main/java/chathealth/chathealth/controller/ViewController.java, src/main/java/chathealth/chathealth/dto/response/PostResponseDetails.java, src/main/java/chathealth/chathealth/repository/MaterialRepository.java, src/main/java/chathealth/chathealth/repository/PicturePostRepository.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/static/css/layout.css, src/main/resources/templates/post/write.html, src/main/resources/templates/view/view.html
=> fetch: viewPage 등록된정보 db에뿌리기

src/main/java/chathealth/chathealth/controller/ViewController.java, src/main/java/chathealth/chathealth/entity/PictureReView.java, src/main/java/chathealth/chathealth/entity/Review.java, src/main/java/chathealth/chathealth/entity/post/PicturePost.java, src/main/resources/static/css/layout.css, src/main/resources/templates/view/reView.html
리뷰 틀 생성과 리뷰사진 테이블 생성해놨습니다! 나중에 괜찮을때 create로 테이블생성한번해주시면 감사하겠습니다
=> fetch: reView front,PictureReView Entity

src/main/java/chathealth/chathealth/controller/IndexController.java, src/main/java/chathealth/chathealth/controller/MemberController.java, src/main/java/chathealth/chathealth/dto/response/PostLikeDto.java, src/main/java/chathealth/chathealth/dto/response/UserInfoDto.java, src/main/java/chathealth/chathealth/entity/post/PostLike.java, src/main/java/chathealth/chathealth/repository/MemberRepository.java, src/main/java/chathealth/chathealth/repository/PostLikeRepository.java, src/main/java/chathealth/chathealth/service/AuthService.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/java/chathealth/chathealth/service/OAuth2DetailsService.java, src/main/resources/templates/fragment/header.html, src/main/resources/templates/index.html, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html
* 인덱스 마이페이지 버튼 링크걸기
* 마이페이지 입장하자마자 유저인포 기본 보이기 (원래 수동이었음....)
* 유저 마이페이지는 내 관심상품 목록 보기(한다고 했는데 실제 좋아요 한 상품이 없어서 작동여부 확인불가, 추후 확인필요)
=> Feat mypage likepost

src/main/java/chathealth/chathealth/controller/MemberController.java, src/main/java/chathealth/chathealth/dto/request/EntEditDto.java, src/main/java/chathealth/chathealth/dto/request/UserEditDto.java, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html
=> Feat: mypage infoupdate

src/main/java/chathealth/chathealth/config/EmailConfig.java, src/main/java/chathealth/chathealth/controller/MemberController.java, src/main/java/chathealth/chathealth/dto/request/EntJoinDto.java, src/main/java/chathealth/chathealth/dto/request/UserJoinDto.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/service/AuthService.java, src/main/java/chathealth/chathealth/service/MailService.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/resources/templates/auth/ent-join.html, src/main/resources/templates/auth/user-join.html, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html
* 본인인증 후 진행 가능하도록 이메일 인증 구현.
* 비밀번호 변경. 비밀번호 변경해도 바로 로그아웃되진 않게 함.
* 개발 편의를 위해 비밀번호가 정규식 조건에 맞지 않아도 가입 가능하도록 했으나, 유효성검사 추가하여 더이상 못하게 잠궜습니다.
=> Feat change pw

src/main/java/chathealth/chathealth/constants/Constants.java, src/main/java/chathealth/chathealth/exception/ExpiredSession.java, src/main/java/chathealth/chathealth/repository/post/PostRepositoryImpl.java, src/main/java/chathealth/chathealth/service/MessageService.java, src/main/resources/templates/fragment/header.html
페이지 바뀔 때마다 sse 연결이 끊겼다 다시 연결이 되므로 문제 없다고 판단.
count 중복 안되게 distinct
=> fix: 페이지 바뀔 때마다 오류 뜨는거 수정, postCount를 distinct

src/main/java/chathealth/chathealth/config/SecurityConfig.java, src/main/java/chathealth/chathealth/constants/Role.java, src/main/java/chathealth/chathealth/controller/AuthController.java, src/main/java/chathealth/chathealth/entity/member/Member.java, src/main/java/chathealth/chathealth/repository/MemberRepository.java, src/main/java/chathealth/chathealth/service/AuthService.java, src/main/java/chathealth/chathealth/service/MemberService.java, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html
* 보통 soft Delete 된 자료들을 거르고 조회 할 때는 Entity에 @ Where 어노테이션을 이용해서 조건절 조회를 진행하나, 해당 어노테이션은 Spring Boot Data JPA ver.6.3부터 deprecated. 따라서 유저를 조회하는 loadByUsername 메서드 내에서 걸렀다.
* util로 빠진 이미지처리 메서드 도입, 가입 및 프로필 변경에 적용.
* Role - [ROLE_WITHDRAW_MEMEBR] 추가
* @SQLDelete 어노테이션 삭제
* 마이페이지 이메일인증 레이아웃 생성 메서드로 따로 빼서 리팩토링.
=> Feat member withdraw

src/main/java/chathealth/chathealth/controller/ChatMessageController.java, src/main/java/chathealth/chathealth/controller/ChatRoomController.java, src/main/java/chathealth/chathealth/controller/view/CommentRestController.java, src/main/java/chathealth/chathealth/service/ChatService.java
경로 리팩토링 한게 import문에 적용되지 않아 죄다 error나고 있었음. 수정 완료
=> hotfix: CustomUserDetails 경로 리팩토링한거 import문에 적용

src/main/resources/templates/view/view.html
이슈 이름과상관없이 view에 문제가 발생해서 급히 수정했습니다
=> Fix: 뷰 오류 수정

src/main/java/chathealth/chathealth/controller/view/ViewController.java, src/main/java/chathealth/chathealth/dto/request/PostHitCountDto.java, src/main/java/chathealth/chathealth/entity/post/PostHit.java, src/main/java/chathealth/chathealth/repository/PostHitRepository.java, src/main/java/chathealth/chathealth/repository/post/PostRepositoryImpl.java, src/main/java/chathealth/chathealth/service/PostService.java
post 조회수생성
12시간을 기준으로 postHit테이블에 추가
=> Posthitprocess

src/main/java/chathealth/chathealth/controller/AuthController.java, src/main/java/chathealth/chathealth/controller/MemberController.java, src/main/java/chathealth/chathealth/dto/response/member/CustomUserDetails.java, src/main/java/chathealth/chathealth/service/MailService.java, src/main/resources/templates/auth/admin.html, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html, src/test/java/chathealth/chathealth/controller/MemberControllerTest.java, src/test/java/chathealth/chathealth/service/PostServiceTest.java
*  if 로그인 유저!=요청 유저, 마이페이지 접근불가. 이로인해 testCode 오류 생겨서 일단 주석처리.
* 멘토링할 때 타 유저정보 보기 눌렀더니 냅다 마이페이지 들어가지고 정보수정 할 수 있는게 너무 충격적이었음.
* 유저에게 보내는 메일 양식 추가.
1. 비밀번호 변경완료 안내메일
2. 탈퇴 완료 안내메일
3. 사업자 계정 권한 변경됨 안내메일
* 관리자가 사용하는 Controller 메서드들 인가 검증처리
=> Fix: 자잘한 인가 검증, UX 개선

src/main/java/chathealth/chathealth/controller/PostController.java, src/main/java/chathealth/chathealth/dto/response/MaterialSeletDto.java, src/main/java/chathealth/chathealth/entity/post/Material.java, src/main/java/chathealth/chathealth/entity/post/Symptom.java, src/main/java/chathealth/chathealth/repository/MaterialRepository.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/templates/layout/layout.html, src/main/resources/templates/post/modify.html, src/main/resources/templates/post/write.html
- Symptom테이블과 Material테이블 관계짓기
- postWrite,postModify에서 증상선택시 관계지어져있는 성분만 선택할 수 있도록 표시
- 증상 멀티셀렉트 기본값은 "증상 선택"으로 하고 이걸로 저장하려고 하면 경고표시
- 증상선택 후 "증상 선택"을 선택시 성분에 아무것도 없도록 처리
- postWrite,postModify layout과 연결
- postWrite,postModify에 필요한 부트스트랩 링크를 헤더에 링크걸어 놓으면 다른 곳에서 영향을 끼쳐서 두개에만 따로 링크 설정
=> update: 증상,성분 테이블 관계 및 css수정

src/main/java/chathealth/chathealth/ChathealthApplication.java, src/main/java/chathealth/chathealth/dto/response/BoardCommentResponse.java, src/main/java/chathealth/chathealth/dto/response/BoardResponse.java, src/main/java/chathealth/chathealth/dto/response/ChatMessageResponse.java, src/main/java/chathealth/chathealth/dto/response/PostModResponseDto.java, src/main/java/chathealth/chathealth/dto/response/PostResponse.java, src/main/java/chathealth/chathealth/dto/response/PostResponseDetails.java, src/main/java/chathealth/chathealth/dto/response/ReViewSelectDto.java, src/main/java/chathealth/chathealth/dto/response/message/MessageSendResponse.java, src/main/java/chathealth/chathealth/service/BoardService.java, src/main/java/chathealth/chathealth/service/ChatService.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/templates/board/board.html, src/main/resources/templates/board/boards.html, src/main/resources/templates/chat/room.html, src/main/resources/templates/fragment/header.html, src/main/resources/templates/post/post.html, src/main/resources/templates/view/view.html, src/test/java/chathealth/chathealth/controller/MemberControllerTest.java
`@PostConstructor` 이용해서 서버 시간을 `Asia/Seoul`로 해놓은 것을 `UTC`로 변경
클라이언트 쪽에서 브라우저 타임존을 기준으로 시간대를 보여주도록 javascript 함수 만들어서 처리하였음
- post.html
- view.html
- header.html
- board.html
- room.html
- boards.html
=> refactor-서버시간 utc 설정.

src/main/java/chathealth/chathealth/controller/view/CommentRestController.java, src/main/java/chathealth/chathealth/controller/view/ViewRestController.java, src/main/java/chathealth/chathealth/dto/request/CommentWriteDto.java, src/main/java/chathealth/chathealth/dto/request/ReviewDto.java, src/main/java/chathealth/chathealth/dto/response/message/ReCommnetSelectDto.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/templates/view/view.html
- 리뷰작성 후 글쓰는창 안비워지는 오류 수정
- 리뷰에 사업자회원은 작성할 수 없도록 수정
- 댓글에 사업자회원의 글이 조회안되는 오류 수정
- 리뷰,댓글에 글자수 제한
=> Fix review & ReComment update

src/main/java/chathealth/chathealth/controller/view/ViewRestController.java, src/main/java/chathealth/chathealth/repository/ReViewRepository.java, src/main/java/chathealth/chathealth/service/PostService.java, src/main/resources/templates/view/view.html
=> Review page

src/main/java/chathealth/chathealth/service/PostService.java
리뷰와 댓글에 프로필값이 null일경우 생기는 오류 수정
=> fix: profile is null

src/main/resources/templates/board/board.html, src/main/resources/templates/board/boards.html, src/main/resources/templates/index.html, src/main/resources/templates/layout/layout.html
1. 승인안된 사업자 회원 로그인 시 인덱스에 정보 안뜸 -> wating -> waiting 오타 수정
2. jquery cdn http -> https로 변경해야함 (https 접속 시 차단됨)
3. profile 사진 null일 때 onerror로 콘솔에 에러 로그 떠서 null 체크 따로 추가
4. role이 admin이거나 uesr일 때만 쪽지 보내기 뜨도록 함
=> fix: html 수정사항 반영

src/main/resources/static/css/layout.css, src/main/resources/templates/member/ent-info.html, src/main/resources/templates/member/user-info.html
* 사업자 마이페이지 기본 프로필사진 설정
* 유저 마이페이지 리뷰 내용도 볼수 있게 수정
=> Fix my page

src/main/resources/templates/member/ent-info.html
=> fix: 사업자 마이페이지 진입 안되던 문제 해결

src/main/resources/static/css/layout.css, src/main/resources/templates/board/board.html, src/main/resources/templates/board/boards.html, src/main/resources/templates/chat/chat.html, src/main/resources/templates/fragment/footer.html, src/main/resources/templates/index.html, src/main/resources/templates/member/user-info.html, src/main/resources/templates/post/post.html, src/main/resources/templates/view/view.html
* `.btn` `.btn-primary` 버튼들은 `.btn-success` 로 통일
* 페이지 상단 고정메뉴 바 색상, index WEEKLY TOP / DAILY TOP 색상 변경
* 삭제 버튼은 `.btn-danger`로 통일
=> Design: 버튼 등 색감 조정

src/main/resources/templates/member/ent-info.html
=> fix: 사업자 회원탈퇴 안되던거 수정

src/main/java/chathealth/chathealth/dto/request/PostWriteDto.java, src/main/resources/static/css/layout.css, src/main/resources/templates/view/view.html
- 리뷰작성 다듬기
- 로그인사용자한테만 리뷰작성보이도록
- post수정,삭제 버튼 수정
=> update: Btn css

src/main/java/chathealth/chathealth/dto/request/member/EntEditDto.java, src/main/java/chathealth/chathealth/dto/request/member/EntJoinDto.java, src/main/java/chathealth/chathealth/dto/request/member/UserEditDto.java, src/main/java/chathealth/chathealth/dto/request/member/UserJoinDto.java
=> Main 브랜치 머지를 위한 컨플릭트 해결

src/test/java/chathealth/chathealth/controller/PostRestControllerTest.java
=> test 오류 주석

src/main/resources/static/css/layout.css, src/main/resources/templates/view/view.html
=> css: fix viewpage css

src/main/resources/templates/board/write.html
=> design: 게시판 글쓰기 제목 텍스트 박스 길이 늘려버림
